
namespace tinyidp.Business.BusinessEntities;

public class AuthorizationRequest
{
    public AuthorizationRequest() { }
    /// <summary>
    /// Response Type, is required
    /// </summary>
    public string response_type { get; set; } = null!;

    /// <summary>
    /// Client Id, is required
    /// </summary>

    public string client_id { get; set; } = null!;

    /// <summary>
    /// Redirect Uri, is optional
    /// The redirection endpoint URI MUST be an absolute URI as defined by
    /// [RFC3986] Section 4.3
    /// </summary>

    public string redirect_uri { get; set; } = null!;

    /// <summary>
    /// Optional
    /// </summary>
    public string scope { get; set; } = null!;

    /// <summary>
    /// Return the state in the result 
    /// if it was present in the client authorization request
    /// </summary>
    public string state { get; set;  } = null!;

    /// <summary>
    /// This is generated by the client
    /// and the Authorization server must return it to client
    /// after generating the identity_token
    /// </summary>
    public string? nonce { get; set; } = null!;

    /// <summary>
    /// if is not null so the client use Pkce
    /// </summary>
    public string? code_challenge { get; set; } = null!;

    /// <summary>
    /// Hasher type for <see cref="code_challenge"/>
    /// </summary>
    public string? code_challenge_method { get; set; } = null!;
}